### ISSUE TITLE
Doubly Linked List [C]

### ISSUE THREAD

**Issue by Monik09** [iiitv/algos#719] opened 2020-08-29 18:30 UTC
#### This issue is about [Doubly Linked List](https://github.com/iiitv/algos)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by Monik09** [comment] 2020-08-29 18:31
@iiitv/project-maintainers I am willing to work on this issue.

**Comment by yashshah2820** [comment] 2020-08-31 16:12
@Monik09 Don't add the external resources link just add the path where the algo will be added inside the repo

**Comment by Monik09** [comment] 2020-08-31 16:31
> @Monik09 Don't add the external resources link just add the path where the algo will be added inside the repo

kk, sir. I will keep that in mind.

**Comment by Monik09** [comment] 2020-09-06 09:14
@iiitv/project-maintainers, can anyone please assign me this issue.

**Comment by yashshah2820** [comment] 2020-09-10 09:45
don't create a PR until the issue is assigned to you

**Closed** 2020-09-29 18:00 UTC
