### ISSUE TITLE
Binary Search [C++]

### ISSUE THREAD

**Issue by abhiy13** [iiitv/algos#643] opened 2018-10-18 17:38 UTC
#### This issue is about [Binary Search](https://en.wikipedia.org/wiki/Binary_search_algorithm).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by shivang-chhabra** [comment] 2019-10-07 08:25
can i resolve this issue?

**Comment by gateway2rohan** [comment] 2019-10-10 16:40
Assign this issue to me

**Comment by sam20code** [comment] 2020-08-28 18:35
@iiitv/project-maintainers    I want to work on this issue

**Comment by yashshah2820** [comment] 2020-08-28 19:09
@sam20code you already have two issues assigned to you, create PRs for them then you can take this issue if no one asks for it in the mean time

**Comment by jatin0814** [comment] 2020-08-28 20:14
I want to work on this issue @iiitv/project-maintainers

**Comment by jatin0814** [comment] 2020-08-29 11:51
@yashshah2820 sir can u please assign it to me

**Comment by yashshah2820** [comment] 2020-08-29 11:53
tag @iiitv/project-maintainers not any individual.

**Comment by yashshah2820** [comment] 2020-08-29 11:54
@jatin0814 don't create a PR until the issue is assigned to you.

**Comment by himanshusanecha** [comment] 2020-08-29 11:55
If possible i want to work on this issue @iiitv/project-maintainers

**Comment by jatin0814** [comment] 2020-08-29 12:00
I already tagged  @iiitv/project-maintainers

**Comment by yashshah2820** [comment] 2020-08-29 12:04
since @jatin0814 asked first so it will be fair enough to assign the issue to him  
GFI 👍

**Comment by himanshusanecha** [comment] 2020-08-29 12:06
no problem sir i will find another one @yashshah2820 😄

**Comment by Ayush-Khandelwal28** [comment] 2022-10-04 03:45
I want to work on the issue, I will also update README. @iiitv/project-maintainers

**Closed** 2022-10-06 19:34 UTC
Labels: lang-cpp, up for grabs, Algorithm, contribute-a-thon
